<a href="https://colab.research.google.com/github/kadobkina/Python_sfedu/blob/master/%D0%9F%D0%B8%D1%82%D0%BE%D0%BD_%D0%B7%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B53.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



---


**Создание одномерных массивов (векторов) и двумерных  массивов (матриц)**

In [ ]:
# 1.Создайте вектор с помощью функции array
np.array([1, 2, 3, 0, 3, 2])

array([1, 2, 3, 0, 3, 2])

In [ ]:
# 1.Создайте матрицу с помощью функции array
np.array([[1, 2, 3], [0, 3, 2]])

array([[1, 2, 3],
       [0, 3, 2]])

In [ ]:
# 2.Создайте вектор с помощью функции arange
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# 2.Создайте матрицу с помощью функции arange
np.arange(0, 12, 2).reshape((2, 3))

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
# 3.Создайте вектор с помощью функции linspace
np.linspace(0, 9, 6)

array([0. , 1.8, 3.6, 5.4, 7.2, 9. ])

In [ ]:
# 3.Создайте матрицу с помощью функции linspace
np.linspace(0, 9, 6).reshape((2, 3))

array([[0. , 1.8, 3.6],
       [5.4, 7.2, 9. ]])

In [ ]:
# 4.Создайте вектор с помощью функции zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# 4.Создайте матрицу с помощью функции zeros
np.zeros(6).reshape((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 5.Создайте вектор с помощью функции full
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# 5.Создайте матрицу с помощью функции full
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])



---


**Модуль random**


In [ ]:
# 6.Создайте двумерный массив случайных чисел с помощью randint
np.random.randint(-10, 10, (2, 4))

array([[-3,  5,  6,  2],
       [-8,  7, -6, -6]])

In [ ]:
# 7.Создайте двумерный массив случайных чисел с помощью uniform
np.random.uniform(-10, 10, (2,4))

array([[-6.49979148, -8.02126602,  4.39904527, -3.45952554],
       [-2.18061882,  2.9699496 ,  1.08757919,  2.14502162]])

In [ ]:
# 8.Создайте двумерный массив случайных чисел с помощью normal
a = np.random.normal(0, 2, (2,4))
a

array([[-1.4398268 ,  2.72896819,  1.41347027,  4.06130191],
       [ 2.98012558, -3.81629678,  0.17113133,  0.54545048]])



---


**Атрибуты массивов, операции с векторами**

In [ ]:
# 9.Выдайте на экран информацию о созданном выше массиве: тип (dtype), размерность (ndim, shape), количество элементов (size), itemsize, nbytes
print(f'Тип: {a.dtype}')
print(f'Размерность: {a.ndim} {a.shape}')
print(f'Количество элементов: {a.size}')
print(f'Размер одного элемента в байтах: {a.itemsize}')
print(f'Размер массива в байтах: {a.nbytes}')

Тип: float64
Размерность: 2 (2, 4)
Количество элементов: 8
Размер одного элемента в байтах: 8
Размер массива в байтах: 64


In [ ]:
# 10.С помощью срезов выделите несколько элементов в массиве и поменяйте их значения
a[:, ::2]=0
a

array([[ 0.        ,  2.72896819,  0.        ,  4.06130191],
       [ 0.        , -3.81629678,  0.        ,  0.54545048]])

In [ ]:
z = np.array([1, 2, 3, 4])
z

array([1, 2, 3, 4])

In [ ]:
v = np.array([2, 4, 6, 9])
v

array([2, 4, 6, 9])

In [ ]:
# 11.Найти результаты арифметических операций для 2 массивов (или числа и массива). 
# Используйте операции или функции numpy(т.е., например, “+” или “np.add”). Вычислите еще любые две функции от массивов.
print(f'z add 5:\n {np.add(z,5)}\n')
print(f'z + 5:\n {z+5}\n')
print(f'z add v:\n {np.add(z,v)}\n')
print(f'z + v:\n {z+v}\n')
print(f'z subtract 3:\n {np.subtract(z,3)}\n')
print(f'z-3:\n {z-3}\n')
print(f'z-v:\n {z-v}\n')
print(f'z multiply 2:\n {np.multiply(z,2)}\n')
print(f'z*2:\n {z*2}\n')
print(f'z*v:\n {z*v}\n')

z add 5:
 [6 7 8 9]

z + 5:
 [6 7 8 9]

z add v:
 [ 3  6  9 13]

z + v:
 [ 3  6  9 13]

z subtract 3:
 [-2 -1  0  1]

z-3:
 [-2 -1  0  1]

z-v:
 [-1 -2 -3 -5]

z multiply 2:
 [2 4 6 8]

z*2:
 [2 4 6 8]

z*v:
 [ 2  8 18 36]





---


**Расстояние, норма и скалярное произведение**

In [ ]:
# 18.Вычислите скалярное произведение двух векторов
np.dot(z,v)

64



---


**Определение матрицы и операции с матрицами**

In [ ]:
x = np.array([[1, 2], [2, 1]])
x

array([[1, 2],
       [2, 1]])

In [ ]:
y = np.array([[6, 5], [5, 6]])
y

array([[6, 5],
       [5, 6]])

In [ ]:
# 19.Создайте 2 матрицы одинакового размера. Найти результаты арифметических операций для 2 матриц. 
# Кроме поэлементного умножения “*”, вычислите еще произведение матриц спомощью функции “np.dot”.
print(f'x add y :\n {np.add(x,y)}\n')
print(f'x + y:\n {x+y}\n')
print(f'x dot y:\n {np.dot(x,y)}\n')
print(f'x * y:\n {x*y}\n')
print(f'x vstack y:\n {np.vstack((x, y))}\n')

x add y :
 [[7 7]
 [7 7]]

x + y:
 [[7 7]
 [7 7]]

x dot y:
 [[16 17]
 [17 16]]

x * y:
 [[ 6 10]
 [10  6]]

x vstack y:
 [[1 2]
 [2 1]
 [6 5]
 [5 6]]



In [ ]:
# 20.Найдите определитель квадратной матрицы
np.linalg.det(y)

11.000000000000002

In [ ]:
# 21.Найдите собственные значения квадратной матрицы
np.linalg.eigvals(x)

array([ 3., -1.])

In [ ]:
# 22.Найдите собственные значения и собственные вектора квадратной матрицы
np.linalg.eigh(x)

(array([-1.,  3.]), array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [ ]:
# 23.Найдите обратную матрицу к квадратной матрице
np.linalg.inv(x)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [ ]:
# 24.Найдите норму квадратной матрицы
np.linalg.norm(x)

3.1622776601683795



---


**Агрегирование.**
Определите произвольный массив. Найдите для него следующие величины (можно по одной из осей или для всего массива):

In [ ]:
r = np.random.randint(-10, 10, 5)
r

array([ 5, -9, -8,  2, -4])

In [ ]:
# 25.Сумму, среднее и минимальное значения
print(f'Сумма = {np.sum(r)}')
print(f'Среднее = {np.mean(r)}')
print(f'Минимальное = {np.min(r)}')

Сумма = -14
Сумма = -2.8
Сумма = -9


In [ ]:
# 26.Произведение, стандартное отклонение и индекс минимального значения
print(f'Произведение = {np.prod(r)}')
print(f'Стандартное отклонение = {np.std(r)}')
print(f'Индекс минимального значения = {np.argmin(r)}')

Произведение = -2880
Стандартное отклонение = 5.491812087098393
Индекс минимального значения = 1


In [ ]:
# 27.Среднее значение, дисперсию и медиану
print(f'Среднее = {np.mean(r)}')
print(f'Дисперсия = {np.var(r)}')
print(f'Медиана = {np.median(r)}')

Среднее = -2.8
Дисперсия = 30.160000000000004
Медиана = -4.0




---


**Сравнения, маски и булева логика**
Определите произвольный массив.



Определите произвольный массив.

In [ ]:
# 28.Найдите количество элементов из промежутка [–5, 5]
np.size(r[(r < 5) & (r >= -5)])

2

In [ ]:
# 29.Определите, есть ли среди его элементов числа большие 100
np.any(r>100)

False

In [ ]:
# 30.Определите, все ли они положительные
np.all(r>0)

False

In [ ]:
# 31.Выбрать из массива все элементы из промежутка [0, 10]
r[(r < 10) & (r >= 0)]

array([5, 2])

In [ ]:
# 32.Заменить в массиве все отрицательные элементы на 0
r[r<0] = 0
r

array([5, 0, 0, 2, 0])



---


**Добавление столбца в матрицу**

Определите произвольную матрицу. Измерьте время работы кода для больших матриц (1000,  10000 и т.д. строк). 
Сделайте это же задание, используя стандартные средства Python, сравните время работы. 

In [ ]:
import time

Numpy - 1000 элементов

In [ ]:
start_time = time.time()

In [ ]:
rr = np.random.randint(0, 10, (1000, 1000))
rr

array([[4, 8, 2, ..., 3, 3, 0],
       [5, 5, 0, ..., 5, 6, 5],
       [4, 6, 5, ..., 4, 8, 1],
       ...,
       [4, 7, 2, ..., 0, 6, 5],
       [1, 7, 4, ..., 5, 5, 4],
       [1, 5, 5, ..., 1, 2, 2]])

In [ ]:
# 33.Посчитайте среднее значение в ее первом столбце. И добавьте в конец матрицы новый столбец из этих средних значений
rr_mean = np.mean(rr[:,:1])
rr_mean

4.66

In [ ]:
temp = np.full((1,1000), rr_mean)
new_rr = np.c_[rr,temp.T]
new_rr

array([[4.  , 8.  , 2.  , ..., 3.  , 0.  , 4.66],
       [5.  , 5.  , 0.  , ..., 6.  , 5.  , 4.66],
       [4.  , 6.  , 5.  , ..., 8.  , 1.  , 4.66],
       ...,
       [4.  , 7.  , 2.  , ..., 6.  , 5.  , 4.66],
       [1.  , 7.  , 4.  , ..., 5.  , 4.  , 4.66],
       [1.  , 5.  , 5.  , ..., 2.  , 2.  , 4.66]])

In [ ]:
print("--- %s seconds with Numpy (1000) ---" % (time.time() - start_time))

--- 0.07608366012573242 seconds with Numpy (1000) ---




---


Numpy - 10000 элементов

In [ ]:
start_time = time.time()

In [ ]:
rr = np.random.randint(0, 10, (10000, 10000))
rr

array([[3, 2, 5, ..., 9, 8, 3],
       [5, 5, 6, ..., 4, 1, 0],
       [6, 0, 2, ..., 7, 8, 2],
       ...,
       [2, 7, 4, ..., 1, 6, 9],
       [0, 2, 1, ..., 2, 2, 1],
       [7, 0, 2, ..., 0, 6, 0]])

In [ ]:
rr_mean = np.mean(rr[:,:1])
rr_mean

4.5013

In [ ]:
temp = np.full((1,10000), rr_mean)
new_rr = np.c_[rr,temp.T]
new_rr

array([[3.    , 2.    , 5.    , ..., 8.    , 3.    , 4.5013],
       [5.    , 5.    , 6.    , ..., 1.    , 0.    , 4.5013],
       [6.    , 0.    , 2.    , ..., 8.    , 2.    , 4.5013],
       ...,
       [2.    , 7.    , 4.    , ..., 6.    , 9.    , 4.5013],
       [0.    , 2.    , 1.    , ..., 2.    , 1.    , 4.5013],
       [7.    , 0.    , 2.    , ..., 6.    , 0.    , 4.5013]])

In [ ]:
print("--- %s seconds with Numpy (10000) ---" % (time.time() - start_time))

--- 2.82389760017395 seconds with Numpy (10000) ---




---


Standart methods - 1000 элементов

In [ ]:
import random
import math

In [ ]:
start_time = time.time()

In [ ]:
mat = []
for i in range(1000):
    rowList = []
    for j in range(1000):
        rowList.append(random.randint(0, 10))
    mat.append(rowList)

In [ ]:
mat[999][0]

4

In [ ]:
s = 0
for i in range(1000):
    s += mat[i][0]
mat_avg = s/1000
mat_avg

5.029

In [ ]:
temp_mat = []
for i in range(1000):
    temp_mat.append(mat_avg)
temp_mat[999]

5.029

In [ ]:
trans_mat = [[mat[j][i] for j in range(len(mat))] for i in range(len(mat[0]))]
trans_mat[0][999]

4

In [ ]:
trans_mat.append(temp_mat)

In [ ]:
len(trans_mat)

1001

In [ ]:
len(trans_mat[0])

1000

In [ ]:
new_mat = [[trans_mat[j][i] for j in range(len(trans_mat))] for i in range(len(trans_mat[0]))]

In [ ]:
len(new_mat)

1000

In [ ]:
len(new_mat[0])

1001

In [ ]:
new_mat[0][1000]

5.029

In [ ]:
print("--- %s seconds with standart methods (1000) ---" % (time.time() - start_time))

--- 2.3507156372070312 seconds with standart methods (1000) ---




---


Standart methods - 10000 элементов (очень долго, решила даже не ждать)

In [ ]:
start_time = time.time()

In [ ]:
mat = []
for i in range(10000):
    rowList = []
    for j in range(10000):
        rowList.append(random.randint(0, 10))
    mat.append(rowList)

In [ ]:
s = 0
for i in range(10000):
    s += mat[i][0]
mat_avg = s/10000
mat_avg

In [ ]:
temp_mat = []
for i in range(10000):
    temp_mat.append(mat_avg)

In [ ]:
trans_mat = [[mat[j][i] for j in range(len(mat))] for i in range(len(mat[0]))]

In [ ]:
trans_mat.append(temp_mat)

In [ ]:
len(trans_mat)

In [ ]:
len(trans_mat[0])

In [ ]:
new_mat = [[trans_mat[j][i] for j in range(len(trans_mat))] for i in range(len(trans_mat[0]))]

In [ ]:
len(new_mat)

In [ ]:
len(new_mat[0])

In [ ]:
new_mat[0][10000]

In [ ]:
print("--- %s seconds with standart methods (10000) ---" % (time.time() - start_time))

*(После решения этого задания я осознала, что надо было делать не все подряд, но было уже поздно........ Так что оставлю их)*



---

**Сортировка.** Определите произвольный двумерный массив.


In [ ]:
m = np.array([[3,1,2], [7,8,3]])
m

array([[3, 1, 2],
       [7, 8, 3]])

In [ ]:
# 36.Отсортируйте в матрице строки
np.sort(m)

array([[1, 2, 3],
       [3, 7, 8]])



---


**Сохранение в файл и загрузка из файла**

In [ ]:
# 42.Сохраните  массив  в  текстовый  файл  (np.savetxt)  и  прочитайте  его  из  файла (np.loadtxt)
np.savetxt('save_array.txt', m)
np.loadtxt('save_array.txt')

array([[3., 1., 2.],
       [7., 8., 3.]])